dd5.loader.jsonp.load_rules( { 'version':'alpha',
'source' : 'basic_pc',
'entity': [
   { type:'ability', id:'str', physical:1 },
   { type:'ability', id:'dex', physical:1 },
   { type:'ability', id:'con', physical:1 },
   { type:'ability', id:'int', mental:1   },
   { type:'ability', id:'wis', mental:1   },
   { type:'ability', id:'cha', mental:1   },

   { type:'proficiency', id:'language' },
   { type:'proficiency', id:'skill'    },
   { type:'proficiency', id:'save'     },
   { type:'proficiency', id:'tool'     },
   { type:'proficiency', id:'weapon'   },
   { type:'proficiency', id:'armour'   },

   { type:'skill', id:'athletic',      ability:'str', physical:1 },
   { type:'skill', id:'acrobatics',    ability:'dex', physical:1 },
   { type:'skill', id:'sleightofhand', ability:'dex', physical:1 },
   { type:'skill', id:'stealth',       ability:'dex', physical:1 },
   { type:'skill', id:'arcana',        ability:'int', mental:1, knowledge:1 },
   { type:'skill', id:'history',       ability:'int', mental:1, knowledge:1 },
   { type:'skill', id:'nature',        ability:'int', mental:1, knowledge:1 },
   { type:'skill', id:'religion',      ability:'int', mental:1, knowledge:1 },
   { type:'skill', id:'animalhandling',ability:'wis', mental:1  },
   { type:'skill', id:'insight',       ability:'wis', mental:1, social:1  },
   { type:'skill', id:'medicine',      ability:'wis', mental:1  },
   { type:'skill', id:'perception',    ability:'wis', mental:1  },
   { type:'skill', id:'survival',      ability:'wis', mental:1  },
   { type:'skill', id:'deception',     ability:'cha', mental:1, social:1 },
   { type:'skill', id:'intimidation',  ability:'cha', mental:1, social:1 },
   { type:'skill', id:'performance',   ability:'cha', mental:1, social:1 },
   { type:'skill', id:'persuasion',    ability:'cha', mental:1, social:1 },

   { type:'language' , id:'common',     letter:'common',    rarity:'standard' },
   { type:'language' , id:'dwarvish',   letter:'dwarvish',  rarity:'standard' },
   { type:'language' , id:'elvish',     letter:'elvish',    rarity:'standard' },
   { type:'language' , id:'giant',      letter:'dwarvish',  rarity:'standard' },
   { type:'language' , id:'gnomish',    letter:'dwarvish',  rarity:'standard' },
   { type:'language' , id:'goblin',     letter:'dwarvish',  rarity:'standard' },
   { type:'language' , id:'halfing',    letter:'common',    rarity:'standard' },
   { type:'language' , id:'orc',        letter:'dwarvish',  rarity:'standard' },

   { type:'language' , id:'abyssal',    letter:'infernal',  rarity:'exotic' },
   { type:'language' , id:'celestial',  letter:'celestial', rarity:'exotic' },
   { type:'language' , id:'draconic',   letter:'draconic',  rarity:'exotic' },
   { type:'language' , id:'deepspeech', letter: null,       rarity:'exotic' },
   { type:'language' , id:'infernal',   letter: 'infernal', rarity:'exotic' },
   { type:'language' , id:'primordial', letter: 'dwarvish', rarity:'exotic' },
   { type:'language' , id:'sylvan',     letter: 'elvish',   rarity:'exotic' },
   { type:'language' , id:'undercommon',letter: 'elvish',   rarity:'exotic' },

   { type:'alignment', id:'lg', lawful:1, chaotic:0, good:1, evil:0 },
   { type:'alignment', id:'ng', lawful:0, chaotic:0, good:1, evil:0 },
   { type:'alignment', id:'cg', lawful:0, chaotic:1, good:1, evil:0 },
   { type:'alignment', id:'ln', lawful:1, chaotic:0, good:0, evil:0 },
   { type:'alignment', id:'tn', lawful:0, chaotic:0, good:0, evil:0 },
   { type:'alignment', id:'cn', lawful:0, chaotic:1, good:0, evil:0 },
   { type:'alignment', id:'le', lawful:1, chaotic:0, good:0, evil:1 },
   { type:'alignment', id:'ne', lawful:0, chaotic:0, good:0, evil:1 },
   { type:'alignment', id:'ce', lawful:0, chaotic:1, good:0, evil:1 },

   { type:'gender', id:'male' },
   { type:'gender', id:'female' },
   { type:'gender', id:'gender-x' },
   { type:'gender', id:'gender-t' },
   { type:'gender', id:'gender-other' },
],
'character': [
   { id: 'system', subrules: [ // Implementation of basec system rules
      ' adj.str_mod  : floor( ( you.str - 10 ) / 2 ) ', ' adj.dex_mod  : floor( ( you.dex - 10 ) / 2 ) ',
      ' adj.con_mod  : floor( ( you.con - 10 ) / 2 ) ', ' adj.int_mod  : floor( ( you.int - 10 ) / 2 ) ',
      ' adj.wis_mod  : floor( ( you.wis - 10 ) / 2 ) ', ' adj.cha_mod  : floor( ( you.cha - 10 ) / 2 ) ',
      ' adj.str_half : floor( you.str_mod / 2 ) ', ' adj.dex_half : floor( you.dex_mod / 2 ) ',
      ' adj.con_half : floor( you.con_mod / 2 ) ', ' adj.int_half : floor( you.int_mod / 2 ) ',
      ' adj.wis_half : floor( you.wis_mod / 2 ) ', ' adj.cha_half : floor( you.cha_mod / 2 ) ',
      ' adj.str_chk  : you.str_mod ', ' adj.dex_chk  : you.dex_mod ',
      ' adj.con_chk  : you.con_mod ', ' adj.int_chk  : you.int_mod ',
      ' adj.wis_chk  : you.wis_mod ', ' adj.cha_chk  : you.cha_mod ',
      ' adj.str_save : you.str_mod ', ' adj.dex_save : you.dex_mod ',
      ' adj.con_save : you.con_mod ', ' adj.int_save : you.int_mod ',
      ' adj.wis_save : you.wis_mod ', ' adj.cha_save : you.cha_mod ',
      ' adj.athletic       : you.str_mod ',
      ' adj.acrobatics     : you.dex_mod ',
      ' adj.sleightofhand  : you.dex_mod ',
      ' adj.stealth        : you.dex_mod ',
      ' adj.arcana         : you.int_mod ',
      ' adj.history        : you.int_mod ',
      ' adj.nature         : you.int_mod ',
      ' adj.religion       : you.int_mod ',
      ' adj.animalhandling : you.wis_mod ',
      ' adj.insight        : you.wis_mod ',
      ' adj.medicine       : you.wis_mod ',
      ' adj.perception     : you.wis_mod ',
      ' adj.survival       : you.wis_mod ',
      ' adj.deception      : you.cha_mod ',
      ' adj.intimidation   : you.cha_mod ',
      ' adj.performance    : you.cha_mod ',
      ' adj.persuasion     : you.cha_mod ',
   ] },
   { id: 'pc', subrules: [ // Standard PC
      ' include : db.character( "system" ) ',
      { feature: 'pc_ability', subrules: [
         ' numSlot.str : 10 [3,18] ',
         ' numSlot.dex : 10 [3,18] ',
         ' numSlot.con : 10 [3,18] ',
         ' numSlot.int : 10 [3,18] ',
         ' numSlot.wis : 10 [3,18] ',
         ' numSlot.cha : 10 [3,18] ',
      ] },
      ' slot.alignment : db.entity({ type: "alignment" }) ',
      ' slot.race : db.race() ',
   ] },
],
'race': [
   { id: 'dwarf', subrules: [
      ' slot.gender : db.entity({ type: "gender" }) ',
      ' adj.speed : 25 ',
      ' adj.size : 3 ',
      ' adj.con : 2 ',
      ' prof.language : common, dwarvish ',
      ' slot.subrace : db.feature({ type: "subrace", of: "dwarf" }) '
   ] },
   { id: 'elf', subrules: [
      ' slot.gender : db.entity({ type: "gender" }) ',
      ' adj.speed : 30 ',
      ' adj.size : 3 ',
      ' adj.dex : 2 ',
      ' prof.language : common, elvish ',
      ' slot.subrace : db.feature({ type: "subrace", of: "elf" }) '
   ] },
   { id: 'halfling', subrules: [
      ' slot.gender : db.entity({ type: "gender" }) ',
      ' adj.speed : 25 ',
      ' adj.size : 2 ',
      ' adj.dex : 2 ',
      ' prof.language : common, halfing ',
      ' slot.subrace : db.feature({ type: "subrace", of: "halfling" }) '
   ] },
   { id: 'human', subrules: [
      ' slot.gender : db.entity({ type: "gender" }) ',
      ' adj.speed : 30 ',
      ' adj.size : 3 ',
      ' prof.language : common ',
      ' profSlot.language.bonus_language : db.entity({ type: "language", rarity: "standard" }) ',
      ' slot.subrace : db.feature({ type: "subrace", of: "human" }) '
   ] },
],
'feature' : [
   { id: 'dwarf-hill', type: 'subrace', of: 'dwarf', subrules: [
      ' adj.wis : 1 ',
   ] },
   { id: 'dwarf-mountain', type: 'subrace', of: 'dwarf', subrules: [
      ' adj.str : 2 ',
   ] },
   { id: 'elf-high', type: 'subrace', of: 'elf', subrules: [
      ' adj.int : 1 ',
      ' profSlot.language.bonus_language : db.entity({ type: "language", rarity: "standard" }) ',
   ] },
   { id: 'elf-wood', type: 'subrace', of: 'elf', subrules: [
      ' adj.wis : 1 ',
      ' adj.speed : 5 ',
   ] },
   { id: 'halfling-lightfoot', type: 'subrace', of: 'halfling', subrules: [
      ' adj.cha : 1 ',
   ] },
   { id: 'halfling-stout', type: 'subrace', of: 'halfling', subrules: [
      ' adj.con : 1 ',
   ] },
   { id: 'human-basic', type: 'subrace', of: 'human', subrules: [
      { adj: 'toCId( db.entity({ type: "ability" }) )', value: 1 }, // Increase ALL abilities by one
   ] },
   { id: 'human-phb', type: 'subrace', of: 'human', subrules: [
      { slot : 'bonus_ability', options : 'db.entity({ type: "ability" })', count: 2 },
      { adj : 'toCId( you.bonus_ability )', value: 1, dependent_attribute: 'bonus_ability' },
      'slot.feat : db.feat() ',
   ] },
],
/*
//      ' set.prof_mod : [ 2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6 ][ you.level ] ',
//      ' adj.str_sv   : you.prof_str_sv ? you.prof_mod : 0 ',
      { 'slot':'bonus_language', 'count':'you.int_mod', 'options':'#entity({type:language,rarity:common})' },
      { 'slot':'background', 'options':'#background' },
      { 'slot':'level'  , 'min_val': 1, 'max_val': 20, 'default': 1 },
      { 'slot':'level_1', 'level':'1', 'options':'#class' },
      { 'slot':'level_2', 'level':'2', 'options':'#class' },
      { 'slot':'level_3', 'level':'3', 'options':'#class' }
   ]
}*/
} );